version: "{build}"

environment:
  matrix:
    - NODEJS_VERSION: "18" # Актуальная версия Node.js

install:
  - ps: Install-Product node $env:NODEJS_VERSION
  - npm install

build_script:
  - npm run build # Сборка проекта

test_script:
  - npm test # Запуск тестов